---
deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH="/home/ucuq4438/public_html"
    
    # Copy all PHP files
    - /bin/cp -R src $DEPLOYPATH/
    - /bin/cp -R public $DEPLOYPATH/
    - /bin/cp index.php $DEPLOYPATH/
    
    # Copy configuration (without .env for security)
    - /bin/cp .htaccess $DEPLOYPATH/ 2>/dev/null || true
    
    # Create .env file on server with production values
    - echo "DB_HOST=localhost" > $DEPLOYPATH/.env
    - echo "DB_PORT=3306" >> $DEPLOYPATH/.env
    - echo "DB_USER=ucuq4438_root" >> $DEPLOYPATH/.env
    - echo "DB_PASSWORD=tubesPWDsemangat" >> $DEPLOYPATH/.env
    - echo "DB_NAME=ucuq4438_pwd" >> $DEPLOYPATH/.env
    
    # Set permissions
    - chmod 600 $DEPLOYPATH/.env
    - chmod -R 755 $DEPLOYPATH/src
    - chmod -R 755 $DEPLOYPATH/public
